// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Activity struct {
	To   string `json:"to"`
	From string `json:"from"`
	Tipe string `json:"tipe"`
}

type Billing struct {
	ID     string `json:"id"`
	UserID int    `json:"user_id"`
	Day    int    `json:"day"`
	Month  int    `json:"month"`
	Year   int    `json:"year"`
	Tipe   string `json:"tipe"`
}

type Category struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Subscriber string `json:"subscriber"`
}

type Channel struct {
	ID          string `json:"id"`
	UserID      int    `json:"user_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Stats       string `json:"stats"`
	Subscriber  int    `json:"subscriber"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	IconPath    string `json:"icon_path"`
	ArtPath     string `json:"art_path"`
	ChannelLink string `json:"channel_link"`
}

type Comment struct {
	ID        string `json:"id"`
	UserID    int    `json:"user_id"`
	VideoID   int    `json:"video_id"`
	Like      int    `json:"like"`
	Dislike   int    `json:"dislike"`
	Day       int    `json:"day"`
	Month     int    `json:"month"`
	Year      int    `json:"year"`
	Hours     int    `json:"hours"`
	Minutes   int    `json:"minutes"`
	Seconds   int    `json:"seconds"`
	Content   string `json:"content"`
	CommentID int    `json:"comment_id"`
}

type Playlist struct {
	ID          string `json:"id"`
	UserID      int    `json:"user_id"`
	Name        string `json:"name"`
	Views       int    `json:"views"`
	Description string `json:"description"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Visibility  string `json:"visibility"`
	VideoList   string `json:"video_list"`
}

type Post struct {
	ID          string `json:"id"`
	ChannelID   int    `json:"channel_id"`
	PicturePath string `json:"picture_path"`
	Like        int    `json:"like"`
	Dislike     int    `json:"dislike"`
	Content     string `json:"content"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Hours       int    `json:"hours"`
	Minutes     int    `json:"minutes"`
	Seconds     int    `json:"seconds"`
}

type Queue struct {
	ID      string `json:"id"`
	UserID  int    `json:"user_id"`
	VideoID int    `json:"video_id"`
}

type User struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Photourl   string `json:"photourl"`
	Location   string `json:"location"`
	Restricted string `json:"restricted"`
	Premium    string `json:"premium"`
}

type Video struct {
	ID            string `json:"id"`
	ChannelID     int    `json:"channel_id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	Views         int    `json:"views"`
	Like          int    `json:"like"`
	Dislike       int    `json:"dislike"`
	Comment       int    `json:"comment"`
	Visibility    string `json:"visibility"`
	Restrict      string `json:"restrict"`
	Day           int    `json:"day"`
	Month         int    `json:"month"`
	Year          int    `json:"year"`
	Hours         int    `json:"hours"`
	Minutes       int    `json:"minutes"`
	Seconds       int    `json:"seconds"`
	VideoPath     string `json:"video_path"`
	ThumbnailPath string `json:"thumbnail_path"`
	Category      string `json:"category"`
	Location      string `json:"location"`
	Premium       string `json:"premium"`
	Duration      int    `json:"duration"`
}

type NewActivity struct {
	To   string `json:"to"`
	From string `json:"from"`
	Tipe string `json:"tipe"`
}

type NewBilling struct {
	UserID int    `json:"user_id"`
	Day    int    `json:"day"`
	Month  int    `json:"month"`
	Year   int    `json:"year"`
	Tipe   string `json:"tipe"`
}

type NewCategory struct {
	Name       string `json:"name"`
	Subscriber string `json:"subscriber"`
}

type NewChannel struct {
	UserID      int    `json:"user_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Stats       string `json:"stats"`
	Subscriber  int    `json:"subscriber"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	IconPath    string `json:"icon_path"`
	ArtPath     string `json:"art_path"`
	ChannelLink string `json:"channel_link"`
}

type NewComment struct {
	UserID    int    `json:"user_id"`
	VideoID   int    `json:"video_id"`
	Like      int    `json:"like"`
	Dislike   int    `json:"dislike"`
	Day       int    `json:"day"`
	Month     int    `json:"month"`
	Year      int    `json:"year"`
	Hours     int    `json:"hours"`
	Minutes   int    `json:"minutes"`
	Seconds   int    `json:"seconds"`
	Content   string `json:"content"`
	CommentID int    `json:"comment_id"`
}

type NewPlaylist struct {
	UserID      int    `json:"user_id"`
	Name        string `json:"name"`
	Views       int    `json:"views"`
	Description string `json:"description"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Visibility  string `json:"visibility"`
	VideoList   string `json:"video_list"`
}

type NewPost struct {
	ChannelID   int    `json:"channel_id"`
	PicturePath string `json:"picture_path"`
	Like        int    `json:"like"`
	Dislike     int    `json:"dislike"`
	Content     string `json:"content"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Hours       int    `json:"hours"`
	Minutes     int    `json:"minutes"`
	Seconds     int    `json:"seconds"`
}

type NewQueue struct {
	UserID  int `json:"user_id"`
	VideoID int `json:"video_id"`
}

type NewUser struct {
	Name       string `json:"name"`
	Email      string `json:"email"`
	Photourl   string `json:"photourl"`
	Location   string `json:"location"`
	Restricted string `json:"restricted"`
	Premium    string `json:"premium"`
}

type NewVideo struct {
	ChannelID     int    `json:"channel_id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	Views         int    `json:"views"`
	Like          int    `json:"like"`
	Dislike       int    `json:"dislike"`
	Comment       int    `json:"comment"`
	Visibility    string `json:"visibility"`
	Restrict      string `json:"restrict"`
	Day           int    `json:"day"`
	Month         int    `json:"month"`
	Year          int    `json:"year"`
	Hours         int    `json:"hours"`
	Minutes       int    `json:"minutes"`
	Seconds       int    `json:"seconds"`
	VideoPath     string `json:"video_path"`
	ThumbnailPath string `json:"thumbnail_path"`
	Category      string `json:"category"`
	Location      string `json:"location"`
	Premium       string `json:"premium"`
	Duration      int    `json:"duration"`
}
